service: ${self:custom.name}-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 14
  environment:
    SERVICE_NAME: ${self:service}
    SSM_STAGE: ${param:ssm-stage, sls:stage}
    MIDDY_CACHE_ENABLED: true
    MIDDY_CACHE_EXPIRATION_MILLISECONDS: 6000
    POWERTOOLS_LOGGER_LOG_EVENT: ${self:custom.logEvent.${sls:stage}, self:custom.logEvent.default}

plugins:
  - serverless-appsync-plugin
  - serverless-esbuild
  - serverless-export-env
  - serverless-export-outputs
  - serverless-iam-roles-per-function

package:
  individually: true

custom:
  name: contest-manager
  region: ${opt:region, 'us-east-1'}
  logLevel:
    dev: ALL
    test: ALL
    prod: ERROR
    default: ERROR
  logEvent:
    dev: true
    test: true
    prod: false
    default: false
  waf:
    dev: false
    prod: true
    default: false

  # Plugin configuration
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    packager: 'yarn'
    exclude: ['@aws-sdk/*']
  exportOutputs:
    include:
      - UserPoolId
      - UserPoolClientId
      - IdentityPoolId
      - GraphQlApiUrl
      - AmplifyConfigBucket
      - DistributionDomainName
    output:
      file: ./.env.test.local
  export-env:
    overwrite: true
  serverless-iam-roles-per-function:
    defaultInherit: true

appSync:
  name: contest-manager-api
  schema: schema.api.graphql
  authentication:
    type: AMAZON_COGNITO_USER_POOLS
    config:
      awsRegion: ${self:custom.region}
      defaultAction: ALLOW
      userPoolId: !Ref UserPool
  logging:
    level: ${self:custom.logLevel.${sls:stage}, self:custom.logLevel.default}
    retentionInDays: 14
  waf:
    enabled: ${self:custom.waf.${sls:stage}, self:custom.waf.default}
    defaultAction: 'Allow'
    rules:
      - throttle
      - disableIntrospection

  resolvers:
    Query.listUsers:
      kind: UNIT
      dataSource: contestManagerTable
      code: resolvers/listUsers.ts

  dataSources:
    contestManagerTable:
      type: AMAZON_DYNAMODB
      description: 'Contest Manager app table'
      config:
        tableName: !Ref ContestManagerTable

functions:
  confirmUserSignup:
    handler: functions/confirm-user-signup.handler
    environment:
      TABLE_NAME: !Ref ContestManagerTable
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt ContestManagerTable.Arn

resources:
  Resources:
    ContestManagerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.name}-user-pool-${sls:stage}
        Policies:
          PasswordPolicy:
            MinimumLength: 10
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            Required: true
          - Name: tenantId
            Mutable: false
            AttributeDataType: String
        LambdaConfig:
          PostConfirmation: !GetAtt ConfirmUserSignupLambdaFunction.Arn

    UserPoolInvokeConfirmUserSignupLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        FunctionName: !Ref ConfirmUserSignupLambdaFunction
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt UserPool.Arn # TODO will need to be called by other user pools eventually

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.name}-client-${sls:stage}
        GenerateSecret: false
        UserPoolId: !Ref UserPool
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
        PreventUserExistenceErrors: ENABLED

    IdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: ${self:custom.name}-identity-pool-${sls:stage}
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId: !Ref UserPoolClient
            ProviderName: !GetAtt UserPool.ProviderName

    AuthenticatedRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Federated: cognito-identity.amazonaws.com
              Action: sts:AssumeRoleWithWebIdentity
              Condition:
                StringEquals:
                  cognito-identity.amazonaws.com:aud: !Ref IdentityPool
                'ForAnyValue:StringLike':
                  cognito-identity.amazonaws.com:amr: authenticated

    UnauthenticatedRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Federated: cognito-identity.amazonaws.com
              Action: sts:AssumeRoleWithWebIdentity
              Condition:
                StringEquals:
                  cognito-identity.amazonaws.com:aud: !Ref IdentityPool
                'ForAnyValue:StringLike':
                  cognito-identity.amazonaws.com:amr: unauthenticated

    IdentityPoolRoleAttachment:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId: !Ref IdentityPool
        Roles:
          authenticated: !GetAtt AuthenticatedRole.Arn
          unauthenticated: !GetAtt UnauthenticatedRole.Arn

    AmplifyConfigBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName:
          Fn::Sub: ${self:service}-amplify-config-${sls:stage}

    Distribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Origins:
            - DomainName: !GetAtt AmplifyConfigBucket.RegionalDomainName
              Id: S3Origin
              OriginAccessControlId: !Ref OriginAccessControl
              S3OriginConfig:
                OriginAccessIdentity: ''
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: ['GET', 'HEAD', 'OPTIONS']
            CachedMethods: ['GET', 'HEAD', 'OPTIONS']
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # Managed-CORS-S3Origin
            ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd # Managed-CORS-With-Preflight
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none

    OriginAccessControl:
      Type: AWS::CloudFront::OriginAccessControl
      Properties:
        OriginAccessControlConfig:
          Name: !Ref AmplifyConfigBucket
          Description: OAC for ${self:service} Amplify config access
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

    AmplifyConfigBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref AmplifyConfigBucket
        PolicyDocument:
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: !Sub ${AmplifyConfigBucket.Arn}/*
              Principal:
                Service: cloudfront.amazonaws.com
              Condition:
                StringEquals:
                  AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}
            - Effect: Deny
              Principal: '*'
              Action: 's3:*'
              Resource:
                - !Sub ${AmplifyConfigBucket.Arn}/*
                - !GetAtt AmplifyConfigBucket.Arn
              Condition:
                Bool:
                  aws:SecureTransport: false

  Outputs:
    UserPoolId:
      Value: !Ref UserPool
    UserPoolClientId:
      Value: !Ref UserPoolClient
    IdentityPoolId:
      Value: !Ref IdentityPool
    GraphQlApiUrl:
      Value: !GetAtt GraphQlApi.GraphQLUrl
    AmplifyConfigBucket:
      Value: !Ref AmplifyConfigBucket
    DistributionDomainName:
      Value: !GetAtt Distribution.DomainName
