name: dev

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    concurrency: dev-environment
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
          role-session-name: GithubActionsSession

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy temp environment
        run: |
          yarn sls deploy --stage dev-ci --param="ssm-stage=dev"
          yarn sls export-env --all --stage dev-ci --param="ssm-stage=dev"
          node deploy-default-config.js

      - name: Run integration tests
        run: yarn cross-env INTEG_TEST=true jest ./tests/test-cases/integration --silent

      - name: Run e2e tests
        run: yarn jest ./tests/test-cases/e2e --silent

      - name: Destroy temp environment
        run: yarn sls remove --stage dev-ci --param="ssm-stage=dev"

      - name: Deploy to dev
        run: yarn sls deploy --stage dev
